@startuml
left to right direction

actor "Utilisateur" as User
actor "Président du Jury" as President
actor "Système d'Authentification" as Auth

rectangle "Application Goncourt 2025" {
    usecase "Afficher les livres\nd'une sélection" as UC1
    usecase "Afficher toutes les sélections" as UC2
    usecase "Ajouter un livre à la 2e/3e sélection" as UC3
    usecase "Saisir résultats du vote\n(dernier tour)" as UC4
    usecase "S'authentifier" as UC5
}

User --> UC1 #green;line.dashed;text:green
User --> UC2 #green;line.dashed;text:green

President --> UC3 #line:blue;line.bold;
President --> UC4 #line:blue;line.bold;
President --> UC5 #line:blue;line.bold;

UC5 <-- Auth #line:red;line.bold;text:red

@enduml
